language: python
python:
  - 2.7
env:
  - DJANGO=django==1.5.4
  - DJANGO=django==1.6
install:
  - pip install $DJANGO
  - python setup.py -q install
script: cd access_tokens_test && python manage.py test access_tokens
notifications:
  email: false
