language: python
python:
  - 2.7
env:
  - DJANGO=django==1.5.4
  - DJANGO=django==1.6
install:
  - pip install $DJANGO
  - python setup.py -q install
script: cd test_project && python manage.py test require
notifications:
  email: false
